package jsint.compiler;
  /**
    * this file is automatically generated by the jscheme->javac compiler Compiler.scm. 
    * Modify at your own risk!
    */
  import jsint.*;
  import java.lang.reflect.*;
  import java.util.*;
  import jsint.*;
import java.lang.*;
import java.lang.reflect.*;

  
  public class CompileReflection extends jsint.Procedure implements jsint.Function,  Runnable {  
      public int whichcode=0;  // corresponds to a numbering of the toplevel procedures of the program
      public int whichtype=0;  // 0 = user defined procedure, 1 = java literal
      public static final int USER_DEF=0, JAVA_LIT=1;
      public Pair frame;
      public DynamicEnvironment dynEnv;

      public CompileReflection() {
          super();
          dynEnv=Scheme.getInteractionEnvironment();
      }
      public CompileReflection(int t, int n, Pair f) {
          whichtype = t;
          whichcode = n;
          frame = f;
          dynEnv = Scheme.getInteractionEnvironment();
      }
      public CompileReflection(int t, int n, Pair f, DynamicEnvironment d) {
          whichtype = t;
          whichcode = n;
          frame = f;
          dynEnv = d;
      }
  
      private Boolean addImport(String s) {
         jsint.Import.addImport(s);
         return Boolean.TRUE;
      }
  
      public void run() {
        this.invoke(null);
      } 
  
      public Object[] makeArgArray(jsint.Pair args) {
         return new Object[]{args};
      }

      public Object apply(Object[] args) {
      return invoke((Pair)args[0]);
      }
  
      public Object apply(Pair args) {
        return invoke(args);
      }
  
      public Object invoke(Pair args)
      {
        return LCO.eval(invoke1(args));
      }
  
    static Object tmp;
  
  
    public static void load() { 
      new CompileReflection().init();
    }

    public static void load(String shellArgs[]) {
       Scheme.getInteractionEnvironment().setValue(Symbol.intern("shellArgs"), shellArgs);
       load();
    }

    public static void main(String shellArgs[]) {
       Symbol main = jsint.Symbol.intern("main");
       load(shellArgs);
       if (main.isDefined())
          {
             DynamicEnvironment dynEnv = Scheme.getInteractionEnvironment();
             ((jsint.Procedure) (dynEnv.getValue(main))).apply(new Pair(shellArgs,Pair.EMPTY));
          }
     }

      public Object invoke1(Pair args) {
      if (whichtype == USER_DEF) {
       switch (whichcode) {
          case 0: return(_L0(args)); 
          case 1: return(_L1(args)); 
          case 2: return(_L2(args)); 
          case 3: return(_L3(args)); 
          case 4: return(_L4(args)); 
          case 5: return(_L5(args)); 
          case 6: return(_L6(args)); 
          case 7: return(_L7(args)); 
          case 8: return(_L8(args)); 
          case 9: return(_L9(args)); 
          case 10: return(_L10(args)); 
          case 11: return(_L11(args)); 
          case 12: return(_L12(args)); 
          case 13: return(_L13(args)); 
          case 14: return(_L14(args)); 
          case 15: return(_L15(args)); 
          case 16: return(_L16(args)); 
          case 17: return(_L17(args)); 
          case 18: return(_L18(args)); 
          case 19: return(_L19(args)); 
          case 20: return(_L20(args)); 
          case 21: return(_L21(args)); 
          case 22: return(_L22(args)); 
          case 23: return(_L23(args)); 
          case 24: return(_L24(args)); 
          case 25: return(_L25(args)); 
          case 26: return(_L26(args)); 
          case 27: return(_L27(args)); 
          case 28: return(_L28(args)); 
          case 29: return(_L29(args)); 
          case 30: return(_L30(args)); 
          case 31: return(_L31(args)); 
          case 32: return(_L32(args)); 
          case 33: return(_L33(args)); 
          case 34: return(_L34(args)); 
          case 35: return(_L35(args)); 
          case 36: return(_L36(args)); 
          case 37: return(_L37(args)); 

         default:  break;
       }}
      else {
       switch (whichcode) {
          case 0: return(_J0(args)); 
          case 1: return(_J1(args)); 
          case 2: return(_J2(args)); 
          case 3: return(_J3(args)); 
          case 4: return(_J4(args)); 
          case 5: return(_J5(args)); 
          case 6: return(_J6(args)); 
          case 7: return(_J7(args)); 
          case 8: return(_J8(args)); 
          case 9: return(_J9(args)); 
          case 10: return(_J10(args)); 
          case 11: return(_J11(args)); 
          case 12: return(_J12(args)); 
          case 13: return(_J13(args)); 
          case 14: return(_J14(args)); 
          case 15: return(_J15(args)); 
          case 16: return(_J16(args)); 
          case 17: return(_J17(args)); 
          case 18: return(_J18(args)); 
          case 19: return(_J19(args)); 
          case 20: return(_J20(args)); 
          case 21: return(_J21(args)); 
          case 22: return(_J22(args)); 
          case 23: return(_J23(args)); 
          case 24: return(_J24(args)); 
          case 25: return(_J25(args)); 

         default:  break;
       }}



      return null;
      }


  
   public void init() {
     Pair Args = null;
     dynEnv.setValue(Symbol.intern("this"), this);
     Class _p = Primitive.class; // this loads the primitives
addImport("jsint.*");

addImport("java.lang.*");

addImport("java.lang.reflect.*");

dynEnv.setValue(Symbol.intern("demo1"), new CompileReflection(USER_DEF, 0, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("demo2"), new CompileReflection(USER_DEF, 1, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("demo3"), new CompileReflection(USER_DEF, 2, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("demo4"), new CompileReflection(USER_DEF, 3, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("demo5"), new CompileReflection(USER_DEF, 4, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("compileGeneric"), new CompileReflection(USER_DEF, 6, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("unwrap"), new CompileReflection(USER_DEF, 7, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("getClassName"), new CompileReflection(USER_DEF, 8, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("compileGenericField"), new CompileReflection(USER_DEF, 13, new Pair( Args, this.frame), dynEnv));

dynEnv.setValue(Symbol.intern("compileGenericMethod/Constructor"), new CompileReflection(USER_DEF, 37, new Pair( Args, this.frame), dynEnv));

  
   }

 // definitions of global variables 
public static final Object demo1 = Symbol.intern("demo1");

public static final Object demo2 = Symbol.intern("demo2");

public static final Object demo3 = Symbol.intern("demo3");

public static final Object demo4 = Symbol.intern("demo4");

public static final Object demo5 = Symbol.intern("demo5");

public static final Object unwrap = Symbol.intern("unwrap");


 // definitions of Scheme variables defined externally
   static Object addImport= Symbol.intern("addImport");

   static Object compileGeneric= Symbol.intern("compileGeneric");

   static Object member= Symbol.intern("member");

   static Object compileGenericField= Symbol.intern("compileGenericField");

   static Object first= Symbol.intern("first");

   static Object second= Symbol.intern("second");

   static Object third= Symbol.intern("third");

   static Object _61_= Symbol.intern("=");

   static Object length= Symbol.intern("length");

   static Object _62_= Symbol.intern(">");

   static Object compileGenericMethod_47_Constructor= Symbol.intern("compileGenericMethod/Constructor");

   static Object string_45_append= Symbol.intern("string-append");

   static Object list= Symbol.intern("list");

   static Object apply= Symbol.intern("apply");

   static Object equal_63_= Symbol.intern("equal?");

   static Object cons= Symbol.intern("cons");

   static Object getClassName= Symbol.intern("getClassName");

   static Object primitiveWrapperType= Symbol.intern("primitiveWrapperType");

   static Object primitiveClassNamed= Symbol.intern("primitiveClassNamed");

   static Object classNamed= Symbol.intern("classNamed");

   static Object append= Symbol.intern("append");

   static Object constructorTable= Symbol.intern("constructorTable");

   static Object methodTable= Symbol.intern("methodTable");

   static Object null_63_= Symbol.intern("null?");

   static Object _43_= Symbol.intern("+");

   static Object rest= Symbol.intern("rest");

   static Object array_45__62_list= Symbol.intern("array->list");

   static Object moreApplicable= Symbol.intern("moreApplicable");

   static Object not= Symbol.intern("not");

   static Object map= Symbol.intern("map");


 // definitions of quoted terms 
   static Object _C0="java.awt.*";

   static Object _C1=Symbol.intern( "constructor");

   static Object _C2="GridLayout";

   static Object _C3="getFont";

   static Object _C4=new   Integer(121);

   static Object _C5=Symbol.intern( "staticmethod");

   static Object _C6="Font";

   static Object _C7=new   Integer(122);

   static Object _C8=Symbol.intern( "instancemethod");

   static Object _C9="Container";

   static Object _C10="add";

   static Object _C11=new   Integer(123);

   static Object _C12="jsint.*";

   static Object _C13=Symbol.intern( "staticfield");

   static Object _C14="useJavaSyntax";

   static Object _C15="U";

   static Object _C16=new   Integer(124);

   static Object _C17=Symbol.intern( "instancefield");

   static Object _C18="rest";

   static Object _C19="Pair";

   static Object _C20=new   Integer(125);

   static Object _C21=new Pair(Symbol.intern( "staticfield"),Pair.EMPTY);

   static Object _C22=new Pair(Symbol.intern( "instancefield"),Pair.EMPTY);

   static Object _C23=new   Integer(3);

   static Object _C24=new   Integer(0);

   static Object _C25=Boolean.TRUE;

   static Object _C26=Boolean.FALSE;

   static Object _C27="the compiler requires instance fields to specify their class: (.CLASS.method args ...)";

   static Object _C28=new Pair(Symbol.intern( "constructor"),Pair.EMPTY);

   static Object _C29="";

   static Object _C30=new Pair(Symbol.intern( "staticmethod"),Pair.EMPTY);

   static Object _C31=new Pair(Symbol.intern( "instancemethod"),Pair.EMPTY);

   static Object _C32="the compiler requires instance methods to specify their class: (.CLASS.method args ...)";

   static Object _C33="Error in compileGeneric, unknown type ";

   static Object _C34=Pair.EMPTY;

   static Object _C35="(((Boolean) ";

   static Object _C36=new Pair(").booleanValue())",Pair.EMPTY);

   static Object _C37="(((Byte) ";

   static Object _C38=new Pair(").byteValue())",Pair.EMPTY);

   static Object _C39="(((Character) ";

   static Object _C40=new Pair(").charValue())",Pair.EMPTY);

   static Object _C41="(((Short) ";

   static Object _C42=new Pair(").shortValue())",Pair.EMPTY);

   static Object _C43="(((Integer) ";

   static Object _C44=new Pair(").intValue())",Pair.EMPTY);

   static Object _C45="(((Long) ";

   static Object _C46=new Pair(").longValue())",Pair.EMPTY);

   static Object _C47="(((Float) ";

   static Object _C48=new Pair(").floatValue())",Pair.EMPTY);

   static Object _C49="(((Double) ";

   static Object _C50=new Pair(").doubleValue())",Pair.EMPTY);

   static Object _C51="((";

   static Object _C52=") ";

   static Object _C53=new Pair(")",Pair.EMPTY);

   static Object _C54="[]";

   static Object _C55="public static ";

   static Object _C56=" ";

   static Object _C57="( Pair Args ){\n                  if (Args.length() == 0) return new ";

   static Object _C58="( ";

   static Object _C59=".";

   static Object _C60=");\n";

   static Object _C61="\n                  else if (Args.length() == 1) \n                     return new ";

   static Object _C62="(";

   static Object _C63=" \n                     = (";

   static Object _C64=" Args.first";

   static Object _C65=new Pair(" ));\n",Pair.EMPTY);

   static Object _C66="\n                  else {System.out.println(\"too many args in call to static field\" + \"";

   static Object _C67=new Pair("\");\n                        return null;} }\n\n\n",Pair.EMPTY);

   static Object _C68="( Pair Args ){\n";

   static Object _C69="    if (Args.length() == 0) return ";

   static Object _C70=";\n";

   static Object _C71="    else if (Args.length() == 1) return (";

   static Object _C72=" = ((";

   static Object _C73=new Pair(") Args.first ));\n",Pair.EMPTY);

   static Object _C74="    else System.out.println(\"too many args in call to static field\" +\"";

   static Object _C75=new Pair("\"); \n",new Pair("    return null; }\n\n\n",Pair.EMPTY));

   static Object _C76="( Pair Args ){\n                   if (Args.length() == 1) return new ";

   static Object _C77="((( ";

   static Object _C78=") (Args.first)).";

   static Object _C79=");\n                   else if (Args.length() == 2) return \n                     new ";

   static Object _C80="(((( ";

   static Object _C81="\n                      = ( ";

   static Object _C82="Args.second()";

   static Object _C83=" )));\n                   else {System.out.println(\"wrong number of args in call to static field\" + \"";

   static Object _C84="\");\n                   return null;} }\n\n\n";

   static Object _C85="( Pair Args ){\n             if (Args.length() == 1) return (( ";

   static Object _C86=";\n             else if (Args.length() == 2) return ((( ";

   static Object _C87=") Args.second() ));\n             else System.out.println(\"wrong number of args in call to static field\" + \"";

   static Object _C88="\"); \n                  return null; }\n\n\n";

   static Object _C89="Error in CompileReflection.scm -- unknown member type";

   static Object _C90=new   Integer(1);

   static Object _C91="true";

   static Object _C92="false";

   static Object _C93=new Pair(",",Pair.EMPTY);

   static Object _C94="{";

   static Object _C95=new Pair("}\n",Pair.EMPTY);

   static Object _C96=new Pair("},\n",Pair.EMPTY);

   static Object _C97=new Pair("true",Pair.EMPTY);

   static Object _C98="(args.nth(";

   static Object _C99=") instanceof ";

   static Object _C100=new Pair(") &&\n        ",Pair.EMPTY);

   static Object _C101="if ((numargs== ";

   static Object _C102=")\n        &&\n       ((b== -1) || (_moreApplicable_";

   static Object _C103="[ ";

   static Object _C104="][b]))\n        &&\n       (";

   static Object _C105=")) \n       { b = ";

   static Object _C106=new Pair(";}\n   \n    ",Pair.EMPTY);

   static Object _C107="(((Boolean) (args.nth(";

   static Object _C108=new Pair("))).booleanValue())",Pair.EMPTY);

   static Object _C109="(((Byte) (args.nth(";

   static Object _C110=new Pair("))).byteValue())",Pair.EMPTY);

   static Object _C111="(((Character) (args.nth(";

   static Object _C112=new Pair("))).charValue())",Pair.EMPTY);

   static Object _C113="(((Short) (args.nth(";

   static Object _C114=new Pair("))).shortValue())",Pair.EMPTY);

   static Object _C115="(((Integer) (args.nth(";

   static Object _C116=new Pair("))).intValue())",Pair.EMPTY);

   static Object _C117="(((Long) (args.nth(";

   static Object _C118=new Pair("))).longValue())",Pair.EMPTY);

   static Object _C119="(((Float) (args.nth(";

   static Object _C120=new Pair("))).floatValue())",Pair.EMPTY);

   static Object _C121="(((Double) (args.nth(";

   static Object _C122=new Pair("))).doubleValue())",Pair.EMPTY);

   static Object _C123=") args.nth(";

   static Object _C124="\n            ";

   static Object _C125=",";

   static Object _C126="    case ";

   static Object _C127=": return new ";

   static Object _C128=new Pair("); \n",Pair.EMPTY);

   static Object _C129=": ";

   static Object _C130=new Pair("); break; \n",Pair.EMPTY);

   static Object _C131=new Pair(")); \n",Pair.EMPTY);

   static Object _C132=": return ";

   static Object _C133="target.";

   static Object _C134="ERROR in CompileReflection.scm ";

   static Object _C135="\nstatic boolean [][] _moreApplicable_";

   static Object _C136=" = new boolean[][]{ \n";

   static Object _C137="\n};\n\npublic static ";

   static Object _C138="Object";

   static Object _C139="(Pair args){\n";

   static Object _C140=" target = (";

   static Object _C141=") args.first; args = (Pair) args.rest;\n";

   static Object _C142="int numargs = args.length()";

   static Object _C143=" \n    tmp=null;  // return type, for methods\n    int b= -1; // index of best matching method/constructor\n\n";

   static Object _C144="\ntry {\nswitch (b) {  \n   // jump to the best matching method/constructor\n";

   static Object _C145=new Pair("\n   default: // error\n}\n} catch(Exception e) {throw new JschemeThrowable(e);}; \n return tmp;\n}\n\n",Pair.EMPTY);


 // definitions of embedded lambdas 
 Object _L0(Pair Args){
   Object tmp=null; 
 tmp = ((jsint.Procedure) dynEnv.getValue((Symbol)addImport)).apply(new Pair(_C0,
    Pair.EMPTY));

tmp = new LCO(_J0/* .println */,new Pair((((jsint.Procedure)_J1/* System.out$ */).apply(jsint.Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)compileGeneric)).apply(new Pair(_C1,
    new Pair(_C2,
    new Pair(_C3,
    new Pair(_C4,
    Pair.EMPTY))))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L1(Pair Args){
   Object tmp=null; 
 tmp = ((jsint.Procedure) dynEnv.getValue((Symbol)addImport)).apply(new Pair(_C0,
    Pair.EMPTY));

tmp = new LCO(_J0/* .println */,new Pair((((jsint.Procedure)_J1/* System.out$ */).apply(jsint.Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)compileGeneric)).apply(new Pair(_C5,
    new Pair(_C6,
    new Pair(_C3,
    new Pair(_C7,
    Pair.EMPTY))))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L2(Pair Args){
   Object tmp=null; 
 tmp = ((jsint.Procedure) dynEnv.getValue((Symbol)addImport)).apply(new Pair(_C0,
    Pair.EMPTY));

tmp = new LCO(_J0/* .println */,new Pair((((jsint.Procedure)_J1/* System.out$ */).apply(jsint.Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)compileGeneric)).apply(new Pair(_C8,
    new Pair(_C9,
    new Pair(_C10,
    new Pair(_C11,
    Pair.EMPTY))))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L3(Pair Args){
   Object tmp=null; 
 tmp = ((jsint.Procedure) dynEnv.getValue((Symbol)addImport)).apply(new Pair(_C12,
    Pair.EMPTY));

tmp = new LCO(_J0/* .println */,new Pair((((jsint.Procedure)_J1/* System.out$ */).apply(jsint.Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)compileGeneric)).apply(new Pair(_C13,
    new Pair(_C14,
    new Pair(_C15,
    new Pair(_C16,
    Pair.EMPTY))))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L4(Pair Args){
   Object tmp=null; 
 tmp = ((jsint.Procedure) dynEnv.getValue((Symbol)addImport)).apply(new Pair(_C12,
    Pair.EMPTY));

tmp = new LCO(_J0/* .println */,new Pair((((jsint.Procedure)_J1/* System.out$ */).apply(jsint.Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)compileGeneric)).apply(new Pair(_C17,
    new Pair(_C18,
    new Pair(_C19,
    new Pair(_C20,
    Pair.EMPTY))))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L5(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)member)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C21,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)member)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C22,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)member)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C28,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)member)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C30,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)member)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C31,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(_J5/* E.error */,new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)string_45_append)).apply(new Pair(_C33,
    new Pair(((jsint.Procedure) _J4/* U.stringify */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)list)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY))),
    Pair.EMPTY)),
    Pair.EMPTY))),
    Pair.EMPTY))
  )
  :
  
  (Boolean.FALSE.equals(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_61_)).apply(new Pair(_C23,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)length)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_62_)).apply(new Pair(((jsint.Procedure) _J2/* .length */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(_C24,
    Pair.EMPTY))))
  ?
  _C26
  :
  _C25
  )
  ))
  ?
  new LCO(_J3/* jsint.E.error */,new Pair(_C32,
    new Pair(((jsint.Procedure) _J4/* U.stringify */).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)))
  :
  new LCO(dynEnv.getValue((Symbol)compileGenericMethod_47_Constructor),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))))
  )
  )
  :
  new LCO(dynEnv.getValue((Symbol)compileGenericMethod_47_Constructor),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))))
  )
  :
  new LCO(dynEnv.getValue((Symbol)compileGenericMethod_47_Constructor),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(_C29,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))))
  )
  :
  
  (Boolean.FALSE.equals(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_61_)).apply(new Pair(_C23,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)length)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_62_)).apply(new Pair(((jsint.Procedure) _J2/* .length */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(_C24,
    Pair.EMPTY))))
  ?
  _C26
  :
  _C25
  )
  ))
  ?
  new LCO(_J3/* jsint.E.error */,new Pair(_C27,
    Pair.EMPTY))
  :
  new LCO(dynEnv.getValue((Symbol)compileGenericField),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))))
  )
  )
  :
  new LCO(dynEnv.getValue((Symbol)compileGenericField),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))))
  );


   return tmp; 
}

 Object _L6(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 5, new Pair( Args, this.frame), dynEnv),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    Pair.EMPTY));


   return tmp; 
}

 Object _L7(Pair Args){
   Object tmp=null; 
 tmp = new LCO(dynEnv.getValue((Symbol)apply),new Pair(dynEnv.getValue((Symbol)string_45_append),
    new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J6/* boolean.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J7/* byte.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J8/* char.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J9/* short.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J10/* int.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J11/* long.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J12/* float.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_J13/* double.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C51,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)getClassName)).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C52,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C53,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C49,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C50,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C47,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C48,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C45,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C46,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C43,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C44,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C41,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C42,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C39,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C40,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C37,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C38,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C35,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_C36,
    Pair.EMPTY))),
    Pair.EMPTY)))
  ),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L8(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) _J14/* .isPrimitive */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) _J16/* .isArray */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(_J15/* .getName */,new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY))
  )
  :
  new LCO(dynEnv.getValue((Symbol)string_45_append),new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair(((jsint.Procedure) _J17/* .getComponentType */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(_C54,
    Pair.EMPTY)))
  )
  :
  new LCO(_J15/* .getName */,new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)primitiveWrapperType)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)primitiveClassNamed)).apply(new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))
  );


   return tmp; 
}

 Object _L9(Pair Args){
   Object tmp=null; 
 tmp = new LCO(dynEnv.getValue((Symbol)getClassName),new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY));


   return tmp; 
}

 Object _L10(Pair Args){
   Object tmp=null; 
 tmp = new LCO(dynEnv.getValue((Symbol)apply),new Pair(dynEnv.getValue((Symbol)string_45_append),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C55,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C56,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(7)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C57,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C58,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C60,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(
  (Boolean.FALSE.equals((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)))
  ?
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C61,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C63,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)unwrap)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    new Pair(_C64,
    Pair.EMPTY))),
    new Pair(_C65,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  _C34
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C66,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(_C67,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L11(Pair Args){
   Object tmp=null; 
 tmp = new LCO(dynEnv.getValue((Symbol)string_45_append),new Pair(_C55,
    new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C56,
    new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(7)),
    Pair.EMPTY)),
    new Pair(_C76,
    new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C77,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(_C78,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(_C79,
    new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C80,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(_C78,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(_C81,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)unwrap)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    new Pair(_C82,
    Pair.EMPTY))),
    new Pair(_C83,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair(_C59,
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(3)),
    new Pair(_C84,
    Pair.EMPTY))))))))))))))))))))))));


   return tmp; 
}

 Object _L12(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,((jsint.Procedure) dynEnv.getValue((Symbol)classNamed)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)));

tmp = (( Pair) Args).setEltNover2(3,((jsint.Procedure) _J18/* .getField */).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY))));

tmp = (( Pair) Args).setEltNover2(5,((jsint.Procedure) _J19/* Modifier.isFinal */).apply(new Pair(((jsint.Procedure) _J20/* .getModifiers */).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)));

tmp = (( Pair) Args).setEltNover2(7,((jsint.Procedure) _J21/* .getType */).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)));

tmp = (( Pair) Args).setEltNover2(9,((jsint.Procedure) dynEnv.getValue((Symbol)getClassName)).apply(new Pair((( Pair) Args).getEltNover2(7),
    Pair.EMPTY)));

tmp = (( Pair) Args).setEltNover2(11,new CompileReflection(USER_DEF, 9, new Pair( Args, this.frame), dynEnv));

tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C13,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C17,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(_J5/* E.error */,new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)string_45_append)).apply(new Pair(_C89,
    new Pair(((jsint.Procedure) _J4/* U.stringify */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)list)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))),
    Pair.EMPTY)),
    Pair.EMPTY))),
    Pair.EMPTY))
  )
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) _J14/* .isPrimitive */).apply(new Pair((( Pair) Args).getEltNover2(7),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)string_45_append),new Pair(_C55,
    new Pair((( Pair) Args).getEltNover2(9),
    new Pair(_C56,
    new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    Pair.EMPTY)),
    new Pair(_C85,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(_C78,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(_C86,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(_C78,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(_C72,
    new Pair((( Pair) Args).getEltNover2(9),
    new Pair(_C87,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(_C59,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(_C88,
    Pair.EMPTY))))))))))))))))))))
  :
  new LCO(new CompileReflection(USER_DEF, 11, new Pair( Args, this.frame), dynEnv),new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(11)).apply(new Pair((( Pair) Args).getEltNover2(7),
    Pair.EMPTY)),
    Pair.EMPTY))
  )
  )
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) _J14/* .isPrimitive */).apply(new Pair((( Pair) Args).getEltNover2(7),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)apply),new Pair(dynEnv.getValue((Symbol)string_45_append),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C55,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(9),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C56,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C68,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C69,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C70,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(
  (Boolean.FALSE.equals((( Pair) Args).getEltNover2(5))
  ?
  ((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C71,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C72,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(9),
    new Pair(_C73,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  _C29
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C74,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C59,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(_C75,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  new LCO(new CompileReflection(USER_DEF, 10, new Pair( Args, this.frame), dynEnv),new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(11)).apply(new Pair((( Pair) Args).getEltNover2(7),
    Pair.EMPTY)),
    Pair.EMPTY))
  )
  );


   return tmp; 
}

 Object _L13(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 12, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    Pair.EMPTY)))))));


   return tmp; 
}

 Object _L14(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)list)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)))),
    new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(5))).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)_43_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C90,
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  _C34
  );


   return tmp; 
}

 Object _L15(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,((jsint.Procedure) dynEnv.getValue((Symbol)classNamed)).apply(new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(5)),
    Pair.EMPTY)));

tmp = (( Pair) Args).setEltNover2(3,
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(1)),
    new Pair(_C1,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(1)),
    new Pair(_C8,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(1)),
    new Pair(_C5,
    Pair.EMPTY))))
  ?
  _C34
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)methodTable)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(3)),
    new Pair(_C25,
    Pair.EMPTY))))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)methodTable)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair((((Pair) ((this.frame).nth(2 ))).getEltNover2(3)),
    new Pair(_C26,
    Pair.EMPTY))))
  )
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)constructorTable)).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY))
  ));

tmp = (( Pair) Args).setEltNover2(5,new CompileReflection(USER_DEF, 14, new Pair( Args, this.frame), dynEnv));

tmp = new LCO((( Pair) Args).getEltNover2(5),new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L16(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 15, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    Pair.EMPTY))));


   return tmp; 
}

 Object _L17(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals((( Pair) Args).getEltNover2(1))
  ?
  _C92
  :
  _C91
  );


   return tmp; 
}

 Object _L18(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)append),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(2 ))).getEltNover2(1))).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_61_)).apply(new Pair(((jsint.Procedure) _J23/* Array.getLength */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) _J23/* Array.getLength */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)moreApplicable)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  _C25
  )
  ),
    Pair.EMPTY)),
    new Pair(_C93,
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(1))).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  new LCO(dynEnv.getValue((Symbol)list),new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(2 ))).getEltNover2(1))).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)_61_)).apply(new Pair(((jsint.Procedure) _J23/* Array.getLength */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) _J23/* Array.getLength */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)moreApplicable)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ?
  _C26
  :
  _C25
  )
  ),
    Pair.EMPTY)),
    Pair.EMPTY))
  )
  :
  _C34
  );


   return tmp; 
}

 Object _L19(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 18, new Pair( Args, this.frame), dynEnv));

tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(dynEnv.getValue((Symbol)append),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C94,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY))),
    new Pair(_C96,
    Pair.EMPTY))),
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(1 ))).getEltNover2(3))).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C94,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY))),
    new Pair(_C95,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  _C34
  );


   return tmp; 
}

 Object _L20(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 19, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    Pair.EMPTY));


   return tmp; 
}

 Object _L21(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 17, new Pair( Args, this.frame), dynEnv));

tmp = (( Pair) Args).setEltNover2(3,new CompileReflection(USER_DEF, 20, new Pair( Args, this.frame), dynEnv));

tmp = new LCO((( Pair) Args).getEltNover2(3),new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L22(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 21, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    new Pair(_C26,
    Pair.EMPTY)));


   return tmp; 
}

 Object _L23(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)append),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C98,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C99,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)getClassName)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(_C100,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(1))).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)_43_)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C90,
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C98,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C99,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J22/* .toString */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)getClassName)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(_C53,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  _C97
  );


   return tmp; 
}

 Object _L24(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 23, new Pair( Args, this.frame), dynEnv));

tmp = new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C101,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J23/* Array.getLength */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C102,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C103,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C104,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C105,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    new Pair(_C106,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L25(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 24, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    Pair.EMPTY));


   return tmp; 
}

 Object _L26(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J6/* boolean.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J7/* byte.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J8/* char.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J9/* short.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J10/* int.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J11/* long.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J12/* float.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(_J13/* double.class */,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)getClassName)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C123,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C53,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C121,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C122,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C119,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C120,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C117,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C118,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C115,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C116,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C113,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C114,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C111,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C112,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C109,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C110,
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C107,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((( Pair) Args).getEltNover2(1),
    new Pair(_C108,
    Pair.EMPTY))),
    Pair.EMPTY)))
  );


   return tmp; 
}

 Object _L27(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 26, new Pair( Args, this.frame), dynEnv));

tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)))
  ?
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C124,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)not)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)null_63_)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)))
  ?
  _C56
  :
  _C125
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(1 ))).getEltNover2(1))).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)_43_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C90,
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)rest)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(_C34,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  :
  _C29
  );


   return tmp; 
}

 Object _L28(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 27, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    Pair.EMPTY));


   return tmp; 
}

 Object _L29(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals((( Pair) Args).getEltNover2(1))
  ?
  _C26
  :
  (( Pair) Args).getEltNover2(1)
  );


   return tmp; 
}

 Object _L30(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals((( Pair) Args).getEltNover2(1))
  ?
  new LCO(new CompileReflection(USER_DEF, 29, new Pair( Args, this.frame), dynEnv),new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(1)),
    new Pair(_C8,
    Pair.EMPTY))),
    Pair.EMPTY))
  :
  (( Pair) Args).getEltNover2(1)
  );


   return tmp; 
}

 Object _L31(Pair Args){
   Object tmp=null; 
 tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair(_J24/* void.class */,
    new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) _J14/* .isPrimitive */).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C126,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C132,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(1))).apply(new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(_C128,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C126,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C127,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)primitiveWrapperType)).apply(new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(1))).apply(new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(_C131,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C126,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C129,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair((( Pair) Args).getEltNover2(3),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (((Pair) ((this.frame).nth(0 ))).getEltNover2(1))).apply(new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(_C130,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  );


   return tmp; 
}

 Object _L32(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 28, new Pair( Args, this.frame), dynEnv));

tmp = 
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C1,
    Pair.EMPTY))))
  ?
  
  (Boolean.FALSE.equals(((jsint.Procedure) new CompileReflection(USER_DEF, 30, new Pair( Args, this.frame), dynEnv)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C5,
    Pair.EMPTY))),
    Pair.EMPTY)))
  ?
  
  (Boolean.FALSE.equals(_C25)
  ?
  _C34
  :
  _C134
  )
  :
  new LCO(new CompileReflection(USER_DEF, 31, new Pair( Args, this.frame), dynEnv),new Pair(((jsint.Procedure) _J25/* .getReturnType */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C5,
    Pair.EMPTY))))
  ?
  ((jsint.Procedure) dynEnv.getValue((Symbol)list)).apply(new Pair(_C133,
    new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY)))
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)list)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(3)),
    new Pair(_C59,
    new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))))
  ),
    Pair.EMPTY)))
  )
  :
  new LCO(dynEnv.getValue((Symbol)cons),new Pair(_C126,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)first)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C127,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(((jsint.Procedure) _J15/* .getName */).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)third)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C62,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(new Pair(_C24,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)array_45__62_list)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)second)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    Pair.EMPTY)),
    Pair.EMPTY)),
    Pair.EMPTY))),
    new Pair(_C128,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)))
  );


   return tmp; 
}

 Object _L33(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 32, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    Pair.EMPTY));


   return tmp; 
}

 Object _L34(Pair Args){
   Object tmp=null; 
 tmp = new LCO((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(7)),
    new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L35(Pair Args){
   Object tmp=null; 
 tmp = new LCO((((Pair) ((this.frame).nth(0 ))).getEltNover2(9)),new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(1)),
    new Pair((((Pair) ((this.frame).nth(1 ))).getEltNover2(5)),
    new Pair((( Pair) Args).getEltNover2(1),
    Pair.EMPTY))));


   return tmp; 
}

 Object _L36(Pair Args){
   Object tmp=null; 
 tmp = (( Pair) Args).setEltNover2(1,new CompileReflection(USER_DEF, 16, new Pair( Args, this.frame), dynEnv));

tmp = (( Pair) Args).setEltNover2(3,((jsint.Procedure) (( Pair) Args).getEltNover2(1)).apply(Pair.EMPTY));

tmp = (( Pair) Args).setEltNover2(5,new CompileReflection(USER_DEF, 22, new Pair( Args, this.frame), dynEnv));

tmp = (( Pair) Args).setEltNover2(7,new CompileReflection(USER_DEF, 25, new Pair( Args, this.frame), dynEnv));

tmp = (( Pair) Args).setEltNover2(9,new CompileReflection(USER_DEF, 33, new Pair( Args, this.frame), dynEnv));

tmp = new LCO(dynEnv.getValue((Symbol)apply),new Pair(dynEnv.getValue((Symbol)string_45_append),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C135,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C136,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) (( Pair) Args).getEltNover2(5)).apply(new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C137,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C1,
    Pair.EMPTY))))
  ?
  _C138
  :
  (((Pair) ((this.frame).nth(0 ))).getEltNover2(5))
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C56,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(7)),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C139,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C8,
    Pair.EMPTY))))
  ?
  _C29
  :
  ((jsint.Procedure) dynEnv.getValue((Symbol)string_45_append)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(_C140,
    new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(5)),
    new Pair(_C141,
    Pair.EMPTY)))))
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C142,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C70,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(
  (Boolean.FALSE.equals(((jsint.Procedure) dynEnv.getValue((Symbol)equal_63_)).apply(new Pair((((Pair) ((this.frame).nth(0 ))).getEltNover2(1)),
    new Pair(_C1,
    Pair.EMPTY))))
  ?
  _C138
  :
  (((Pair) ((this.frame).nth(0 ))).getEltNover2(5))
  ),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C143,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)apply)).apply(new Pair(dynEnv.getValue((Symbol)append),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)map)).apply(new Pair(new CompileReflection(USER_DEF, 34, new Pair( Args, this.frame), dynEnv),
    new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY))),
    Pair.EMPTY))),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)cons)).apply(new Pair(_C144,
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)append)).apply(new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)apply)).apply(new Pair(dynEnv.getValue((Symbol)append),
    new Pair(((jsint.Procedure) dynEnv.getValue((Symbol)map)).apply(new Pair(new CompileReflection(USER_DEF, 35, new Pair( Args, this.frame), dynEnv),
    new Pair((( Pair) Args).getEltNover2(3),
    Pair.EMPTY))),
    Pair.EMPTY))),
    new Pair(_C145,
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY))),
    Pair.EMPTY)));


   return tmp; 
}

 Object _L37(Pair Args){
   Object tmp=null; 
 tmp = new LCO(new CompileReflection(USER_DEF, 36, new Pair( Args, this.frame), dynEnv),new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    new Pair(_C26,
    Pair.EMPTY))))));


   return tmp; 
}


 // definitions of java literals
public static Object _J0/* .println */(Pair Args){
  return (((jsint.Procedure)_J0/* .println */).apply(Args));}
static Object _J0/* .println */ = new JavaMethod("println", null, false);

public static java.io.PrintStream _J1/* System.out$ */( Pair Args ){
    if (Args.length() == 0) return System.out;
    else System.out.println("too many args in call to static field" +"System.out"); 
    return null; }


static Object _J1/* System.out$ */ = new CompileReflection( JAVA_LIT, 1/* System.out$*/, Pair.EMPTY);

public static Object _J2/* .length */(Pair Args){
  return (((jsint.Procedure)_J2/* .length */).apply(Args));}
static Object _J2/* .length */ = new JavaMethod("length", null, false);


static boolean [][] _moreApplicable__J3/* jsint.E.error */ = new boolean[][]{ 
{true,false},
{false,true}

};

public static Object _J3/* jsint.E.error */(Pair args){
int numargs = args.length();
Object 
    tmp=null;  // return type, for methods
    int b= -1; // index of best matching method/constructor

if ((numargs== 2)
        &&
       ((b== -1) || (_moreApplicable__J3/* jsint.E.error */[ 0][b]))
        &&
       ((args.nth(0) instanceof java.lang.String) &&
        (args.nth(1) instanceof java.lang.Object))) 
       { b = 0;}
   
    if ((numargs== 1)
        &&
       ((b== -1) || (_moreApplicable__J3/* jsint.E.error */[ 1][b]))
        &&
       ((args.nth(0) instanceof java.lang.String))) 
       { b = 1;}
   
    
try {
switch (b) {  
   // jump to the best matching method/constructor
    case 0: return jsint.E.error(
            (java.lang.String) args.nth(0),
            (java.lang.Object) args.nth(1) ); 
    case 1: return jsint.E.error(
            (java.lang.String) args.nth(0) ); 

   default: // error
}
} catch(Exception e) {throw new JschemeThrowable(e);}; 
 return tmp;
}

static Object _J3/* jsint.E.error */ = new CompileReflection( JAVA_LIT, 3/* jsint.E.error*/, Pair.EMPTY);


static boolean [][] _moreApplicable__J4/* U.stringify */ = new boolean[][]{ 
{true,false,false},
{false,true,false},
{false,false,true}

};

public static Object _J4/* U.stringify */(Pair args){
int numargs = args.length();
Object 
    tmp=null;  // return type, for methods
    int b= -1; // index of best matching method/constructor

if ((numargs== 3)
        &&
       ((b== -1) || (_moreApplicable__J4/* U.stringify */[ 0][b]))
        &&
       ((args.nth(0) instanceof java.lang.Object) &&
        (args.nth(1) instanceof java.lang.Boolean) &&
        (args.nth(2) instanceof java.lang.StringBuffer))) 
       { b = 0;}
   
    if ((numargs== 1)
        &&
       ((b== -1) || (_moreApplicable__J4/* U.stringify */[ 1][b]))
        &&
       ((args.nth(0) instanceof java.lang.Object))) 
       { b = 1;}
   
    if ((numargs== 2)
        &&
       ((b== -1) || (_moreApplicable__J4/* U.stringify */[ 2][b]))
        &&
       ((args.nth(0) instanceof java.lang.Object) &&
        (args.nth(1) instanceof java.lang.Boolean))) 
       { b = 2;}
   
    
try {
switch (b) {  
   // jump to the best matching method/constructor
    case 0: return U.stringify(
            (java.lang.Object) args.nth(0),
            (((Boolean) (args.nth(1))).booleanValue()),
            (java.lang.StringBuffer) args.nth(2) ); 
    case 1: return U.stringify(
            (java.lang.Object) args.nth(0) ); 
    case 2: return U.stringify(
            (java.lang.Object) args.nth(0),
            (((Boolean) (args.nth(1))).booleanValue()) ); 

   default: // error
}
} catch(Exception e) {throw new JschemeThrowable(e);}; 
 return tmp;
}

static Object _J4/* U.stringify */ = new CompileReflection( JAVA_LIT, 4/* U.stringify*/, Pair.EMPTY);


static boolean [][] _moreApplicable__J5/* E.error */ = new boolean[][]{ 
{true,false},
{false,true}

};

public static Object _J5/* E.error */(Pair args){
int numargs = args.length();
Object 
    tmp=null;  // return type, for methods
    int b= -1; // index of best matching method/constructor

if ((numargs== 2)
        &&
       ((b== -1) || (_moreApplicable__J5/* E.error */[ 0][b]))
        &&
       ((args.nth(0) instanceof java.lang.String) &&
        (args.nth(1) instanceof java.lang.Object))) 
       { b = 0;}
   
    if ((numargs== 1)
        &&
       ((b== -1) || (_moreApplicable__J5/* E.error */[ 1][b]))
        &&
       ((args.nth(0) instanceof java.lang.String))) 
       { b = 1;}
   
    
try {
switch (b) {  
   // jump to the best matching method/constructor
    case 0: return E.error(
            (java.lang.String) args.nth(0),
            (java.lang.Object) args.nth(1) ); 
    case 1: return E.error(
            (java.lang.String) args.nth(0) ); 

   default: // error
}
} catch(Exception e) {throw new JschemeThrowable(e);}; 
 return tmp;
}

static Object _J5/* E.error */ = new CompileReflection( JAVA_LIT, 5/* E.error*/, Pair.EMPTY);

public static Object _J6/* boolean.class */(Pair Args){
  return (((jsint.Procedure)_J6/* boolean.class */).apply(Args));}
static Object _J6/* boolean.class */ = boolean.class;

public static Object _J7/* byte.class */(Pair Args){
  return (((jsint.Procedure)_J7/* byte.class */).apply(Args));}
static Object _J7/* byte.class */ = byte.class;

public static Object _J8/* char.class */(Pair Args){
  return (((jsint.Procedure)_J8/* char.class */).apply(Args));}
static Object _J8/* char.class */ = char.class;

public static Object _J9/* short.class */(Pair Args){
  return (((jsint.Procedure)_J9/* short.class */).apply(Args));}
static Object _J9/* short.class */ = short.class;

public static Object _J10/* int.class */(Pair Args){
  return (((jsint.Procedure)_J10/* int.class */).apply(Args));}
static Object _J10/* int.class */ = int.class;

public static Object _J11/* long.class */(Pair Args){
  return (((jsint.Procedure)_J11/* long.class */).apply(Args));}
static Object _J11/* long.class */ = long.class;

public static Object _J12/* float.class */(Pair Args){
  return (((jsint.Procedure)_J12/* float.class */).apply(Args));}
static Object _J12/* float.class */ = float.class;

public static Object _J13/* double.class */(Pair Args){
  return (((jsint.Procedure)_J13/* double.class */).apply(Args));}
static Object _J13/* double.class */ = double.class;

public static Object _J14/* .isPrimitive */(Pair Args){
  return (((jsint.Procedure)_J14/* .isPrimitive */).apply(Args));}
static Object _J14/* .isPrimitive */ = new JavaMethod("isPrimitive", null, false);

public static Object _J15/* .getName */(Pair Args){
  return (((jsint.Procedure)_J15/* .getName */).apply(Args));}
static Object _J15/* .getName */ = new JavaMethod("getName", null, false);

public static Object _J16/* .isArray */(Pair Args){
  return (((jsint.Procedure)_J16/* .isArray */).apply(Args));}
static Object _J16/* .isArray */ = new JavaMethod("isArray", null, false);

public static Object _J17/* .getComponentType */(Pair Args){
  return (((jsint.Procedure)_J17/* .getComponentType */).apply(Args));}
static Object _J17/* .getComponentType */ = new JavaMethod("getComponentType", null, false);

public static Object _J18/* .getField */(Pair Args){
  return (((jsint.Procedure)_J18/* .getField */).apply(Args));}
static Object _J18/* .getField */ = new JavaMethod("getField", null, false);


static boolean [][] _moreApplicable__J19/* Modifier.isFinal */ = new boolean[][]{ 
{true}

};

public static Object _J19/* Modifier.isFinal */(Pair args){
int numargs = args.length();
Object 
    tmp=null;  // return type, for methods
    int b= -1; // index of best matching method/constructor

if ((numargs== 1)
        &&
       ((b== -1) || (_moreApplicable__J19/* Modifier.isFinal */[ 0][b]))
        &&
       ((args.nth(0) instanceof java.lang.Integer))) 
       { b = 0;}
   
    
try {
switch (b) {  
   // jump to the best matching method/constructor
    case 0: return new java.lang.Boolean(Modifier.isFinal(
            (((Integer) (args.nth(0))).intValue()) )); 

   default: // error
}
} catch(Exception e) {throw new JschemeThrowable(e);}; 
 return tmp;
}

static Object _J19/* Modifier.isFinal */ = new CompileReflection( JAVA_LIT, 19/* Modifier.isFinal*/, Pair.EMPTY);

public static Object _J20/* .getModifiers */(Pair Args){
  return (((jsint.Procedure)_J20/* .getModifiers */).apply(Args));}
static Object _J20/* .getModifiers */ = new JavaMethod("getModifiers", null, false);

public static Object _J21/* .getType */(Pair Args){
  return (((jsint.Procedure)_J21/* .getType */).apply(Args));}
static Object _J21/* .getType */ = new JavaMethod("getType", null, false);

public static Object _J22/* .toString */(Pair Args){
  return (((jsint.Procedure)_J22/* .toString */).apply(Args));}
static Object _J22/* .toString */ = new JavaMethod("toString", null, false);


static boolean [][] _moreApplicable__J23/* Array.getLength */ = new boolean[][]{ 
{true}

};

public static Object _J23/* Array.getLength */(Pair args){
int numargs = args.length();
Object 
    tmp=null;  // return type, for methods
    int b= -1; // index of best matching method/constructor

if ((numargs== 1)
        &&
       ((b== -1) || (_moreApplicable__J23/* Array.getLength */[ 0][b]))
        &&
       ((args.nth(0) instanceof java.lang.Object))) 
       { b = 0;}
   
    
try {
switch (b) {  
   // jump to the best matching method/constructor
    case 0: return new java.lang.Integer(Array.getLength(
            (java.lang.Object) args.nth(0) )); 

   default: // error
}
} catch(Exception e) {throw new JschemeThrowable(e);}; 
 return tmp;
}

static Object _J23/* Array.getLength */ = new CompileReflection( JAVA_LIT, 23/* Array.getLength*/, Pair.EMPTY);

public static Object _J24/* void.class */(Pair Args){
  return (((jsint.Procedure)_J24/* void.class */).apply(Args));}
static Object _J24/* void.class */ = void.class;

public static Object _J25/* .getReturnType */(Pair Args){
  return (((jsint.Procedure)_J25/* .getReturnType */).apply(Args));}
static Object _J25/* .getReturnType */ = new JavaMethod("getReturnType", null, false);


    //static { new CompileReflection().init();}
    }
