package jsint;			;
/** This class is generated by src/build/jscheme-bootstrap.scm. **/
public class Version {
  public static final String VERSION =
    "JScheme 7.1 (6/24/04 7:30 AM) http://jscheme.sourceforge.net";
}
